# The labels in this file are automatically synced with the repository
# using the micnncim/action-label-syncer action.
---
# Dependabot
- name: C-dependency
  color: 1abc9c
  description: "Category: Dependency"
- name: PR-block
  color: 3498db
  description: "Pull Request: Do not merge"
- name: PR-merge
  color: 3498db
  description: "Pull Request: Merge when ready"
# Release Drafter
- name: major
  color: 1abc9c
  description: "Make Release drafter create a new major release"
- name: minor
  color: 3498db
  description: "Make Release drafter create a new minor release"
- name: patch
  color: 3498db
  description: "Make Release drafter create a new patch release"
